services:
  watcher-app:
    image: max1234565/changemonitor:latest
    container_name: change-monitor
    restart: unless-stopped
    ports:
      - "8085:8000"
    volumes:
      - /opt/homelab/volumes/change-monitor/data:/data
